<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laundry_packets_model extends CI_Model
{

    public $table = 'laundry_packets';
    public $id = 'laundry_packet_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('laundry_packet_id', $q);
        $this->db->or_like('name', $q);
        $this->db->or_like('price', $q);
        $this->db->or_like('created_at', $q);
        $this->db->or_like('update_at', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('laundry_packet_id', $q);
        $this->db->or_like('name', $q);
        $this->db->or_like('price', $q);
        $this->db->or_like('created_at', $q);
        $this->db->or_like('update_at', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Laundry_packets_model.php */
/* Location: ./application/models/Laundry_packets_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-31 06:55:55 */
/* http://harviacode.com */