<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transfers_report_model extends CI_Model
{

    public $table = 'transfers_report';
    public $id = 'transfer_report_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->load->model('Laundry_packets_model');
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('transfer_report_id', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('examiner_id', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('transaction_id', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('created_on', $q);
	$this->db->or_like('processed_on', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('transfer_report_id', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('examiner_id', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('transaction_id', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('created_on', $q);
	$this->db->or_like('processed_on', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);

        return $this->get_by_id($id);
    }

    function getLaundryPacket($id)
    {
        $this->db->where($this->id, $id);
        $id = $this->db->get($this->table)->row()->id;

        return $this->Laundry_packets_model->get_by_id($id)->row();
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Transfers_report_model.php */
/* Location: ./application/models/Transfers_report_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-06 12:03:56 */
/* http://harviacode.com */